In [ ]:
import sympy as sp
import numpy as np

# Symbols
E, A, I = sp.symbols('E A I', positive=True)
L0, L1, L2, L3 = sp.symbols('L_0 L_1 L_2 L_3', positive=True)
theta_0, theta_1, theta_2, theta_3 = sp.symbols('theta_0 theta_1 theta_2 theta_3')

In [ ]:

def basic_stiffness(E, A, I, L):
    return sp.Matrix([
        [E*A/L,      0,       0],
        [0,     4*E*I/L, 2*E*I/L],
        [0,     2*E*I/L, 4*E*I/L],
    ])

def basic_local_transformation(L):
    return sp.Matrix([
        [-1,    0,    0,   1,    0,    0],
        [ 0,  1/L,    1,   0,  -1/L,   0],
        [ 0,  1/L,    0,   0,  -1/L,   1]
    ])

def local_global_transformation(theta):
    c = sp.cos(theta)
    s = sp.sin(theta)
    return sp.Matrix([
        [ c,  s,  0,  0,  0,  0],
        [-s,  c,  0,  0,  0,  0],
        [ 0,  0,  1,  0,  0,  0],
        [ 0,  0,  0,  c,  s,  0],
        [ 0,  0,  0, -s,  c,  0],
        [ 0,  0,  0,  0,  0,  1],
    ])

def global_stiffness(E, A, I, L, theta):
    kb  = basic_stiffness(E, A, I, L)
    Tbl = basic_local_transformation(L)
    Tlg = local_global_transformation(theta)
    kl  = Tbl.T * kb * Tbl
    kg  = Tlg.T * kl * Tlg
    return kb, Tbl, Tlg, kl, kg

def print_element_summary(name, kb, Tbl, Tlg, kl, kg, decimals=2):
    def fmt(M):
        return sp.Matrix([[sp.nsimplify(v, rational=True) for v in row] for row in M.tolist()])
    
    np.set_printoptions(precision=2, suppress=True, linewidth=200)
    print(f"\n{'='*60}")
    print(f"Element: {name}")
    print(f"{'='*60}")
    print("kb:") ;  sp.pprint(fmt(kb))
    # print("\nTbl:"); sp.pprint(fmt(Tbl))
    # print("\nTlg:"); sp.pprint(fmt(Tlg))
    print("\nkl:");  sp.pprint(fmt(kl))
    print("\nkg:");  sp.pprint(fmt(kg))

In [ ]:
# Elements
kb0, Tbl0, Tlg0, kl0, kg0 = global_stiffness(E, A, I, L0, sp.atan2(3, 2))
kb1, Tbl1, Tlg1, kl1, kg1 = global_stiffness(E, A, I, L1, sp.atan2(0, 2))
kb2, Tbl2, Tlg2, kl2, kg2 = global_stiffness(E, A, I, L2, sp.atan2(0, 1))
kb3, Tbl3, Tlg3, kl3, kg3 = global_stiffness(E, A, I, L3, sp.atan2(-3, 0))

print_element_summary("Element 0", kb0, Tbl0, Tlg0, kl0, kg0)
print_element_summary("Element 1", kb1, Tbl1, Tlg1, kl1, kg1)
print_element_summary("Element 2", kb2, Tbl2, Tlg2, kl2, kg2)
print_element_summary("Element 3", kb3, Tbl3, Tlg3, kl3, kg3)


Element: Element 0
kb:
⎡A⋅E              ⎤
⎢───    0      0  ⎥
⎢L₀               ⎥
⎢                 ⎥
⎢     4⋅E⋅I  2⋅E⋅I⎥
⎢ 0   ─────  ─────⎥
⎢      L₀     L₀  ⎥
⎢                 ⎥
⎢     2⋅E⋅I  4⋅E⋅I⎥
⎢ 0   ─────  ─────⎥
⎣      L₀     L₀  ⎦

kl:
⎡ A⋅E                      -A⋅E                    ⎤
⎢ ───      0         0     ─────     0         0   ⎥
⎢ L₀                        L₀                     ⎥
⎢                                                  ⎥
⎢        12⋅E⋅I    6⋅E⋅I          -12⋅E⋅I    6⋅E⋅I ⎥
⎢  0     ──────    ─────     0    ────────   ───── ⎥
⎢           3         2               3         2  ⎥
⎢         L₀        L₀              L₀        L₀   ⎥
⎢                                                  ⎥
⎢        6⋅E⋅I     4⋅E⋅I          -6⋅E⋅I     2⋅E⋅I ⎥
⎢  0     ─────     ─────     0    ───────    ───── ⎥
⎢           2       L₀                2       L₀   ⎥
⎢         L₀                        L₀             ⎥
⎢                                                  ⎥
⎢-A⋅E    

In [ ]:
# Numerical values
E_val = 200e3
A_val = 200**2 - 190**2
I_val = (200**4 - 190**4)/12 

# Lengths
L0_val = float(sp.sqrt((2-0)**2 + (3-0)**2))*1000
L1_val = float(sp.sqrt((4-2)**2 + (3-3)**2))*1000
L2_val = float(sp.sqrt((5-4)**2 + (3-3)**2))*1000 
L3_val = float(sp.sqrt((5-5)**2 + (0-3)**2))*1000

# Elements
kb0, Tbl0, Tlg0, kl0, kg0 = global_stiffness(E_val, A_val, I_val, L0_val, sp.atan2(3, 2))
kb1, Tbl1, Tlg1, kl1, kg1 = global_stiffness(E_val, A_val, I_val, L1_val, sp.atan2(0, 2))
kb2, Tbl2, Tlg2, kl2, kg2 = global_stiffness(E_val, A_val, I_val, L2_val, sp.atan2(0, 1))
kb3, Tbl3, Tlg3, kl3, kg3 = global_stiffness(E_val, A_val, I_val, L3_val, sp.atan2(-3, 0))

# Numerical matrix
kg0_np = np.array(kg0.tolist(), dtype=float)
kg1_np = np.array(kg1.tolist(), dtype=float)
kg2_np = np.array(kg2.tolist(), dtype=float)
kg3_np = np.array(kg3.tolist(), dtype=float)

print("Element 0", kg0_np)
print('--'*50)
print("Element 1", kg1_np)
print('--'*50)
print("Element 2", kg2_np)
print('--'*50)
print("Element 3", kg3_np)
print('--'*50)

Element 0 [[ 6.74e+04  9.93e+04 -1.90e+06 -6.74e+04 -9.93e+04 -1.90e+06]
 [ 9.93e+04  1.50e+05  1.27e+06 -9.93e+04 -1.50e+05  1.27e+06]
 [-1.90e+06  1.27e+06  5.49e+09  1.90e+06 -1.27e+06  2.74e+09]
 [-6.74e+04 -9.93e+04  1.90e+06  6.74e+04  9.93e+04  1.90e+06]
 [-9.93e+04 -1.50e+05 -1.27e+06  9.93e+04  1.50e+05 -1.27e+06]
 [-1.90e+06  1.27e+06  2.74e+09  1.90e+06 -1.27e+06  5.49e+09]]
----------------------------------------------------------------------------------------------------
Element 1 [[ 3.90e+05  0.00e+00  0.00e+00 -3.90e+05  0.00e+00  0.00e+00]
 [ 0.00e+00  7.42e+03  7.42e+06  0.00e+00 -7.42e+03  7.42e+06]
 [ 0.00e+00  7.42e+06  9.89e+09  0.00e+00 -7.42e+06  4.95e+09]
 [-3.90e+05  0.00e+00  0.00e+00  3.90e+05  0.00e+00  0.00e+00]
 [ 0.00e+00 -7.42e+03 -7.42e+06  0.00e+00  7.42e+03 -7.42e+06]
 [ 0.00e+00  7.42e+06  4.95e+09  0.00e+00 -7.42e+06  9.89e+09]]
----------------------------------------------------------------------------------------------------
Element 2 [[ 7.80e+0

In [ ]:
# Node DOF mapping
n_nodes = 5
n_dof   = 3
n_total = n_nodes * n_dof 

K = np.zeros((n_total, n_total))

# Element connectivity 
connectivity = [
    (0, 1, np.array([0,  1,  2,  3,  4,  5])),
    (1, 2, np.array([3,  4,  5,  6,  7,  8])),
    (2, 3, np.array([6,  7,  8,  9, 10, 11])),
    (3, 4, np.array([9, 10, 11, 12, 13, 14])),
]

kg_list = [kg0_np, kg1_np, kg2_np, kg3_np]

for (ni, nj, idx), kg in zip(connectivity, kg_list):
    print(K)
    print("--"*50)
    for i_local, i_global in enumerate(idx):
        for j_local, j_global in enumerate(idx): 
            K[i_global, j_global] += kg[i_local, j_local]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
----------------------------------------------------------------------------------------------------
[[ 6.74e+04  9.93e+04 -1.90e+06 -6.74e+04 -9.93e+04 -1.90e+06  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 9.93e+04  1.50e+05  1.

In [7]:
# DOF classification
free_dofs       = np.array([3, 4, 5, 6, 7, 8, 9, 10, 11, 14])
restrained_dofs = np.array([0, 1, 2, 12, 13])

# Partitioning
Kff = K[np.ix_(free_dofs, free_dofs)]
Kfr = K[np.ix_(free_dofs, restrained_dofs)]
Krf = K[np.ix_(restrained_dofs, free_dofs)]
Krr = K[np.ix_(restrained_dofs, restrained_dofs)]

print("K:\n", K)
print("\nKff:\n", Kff)

K:
 [[ 6.74e+04  9.93e+04 -1.90e+06 -6.74e+04 -9.93e+04 -1.90e+06  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 9.93e+04  1.50e+05  1.27e+06 -9.93e+04 -1.50e+05  1.27e+06  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-1.90e+06  1.27e+06  5.49e+09  1.90e+06 -1.27e+06  2.74e+09  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-6.74e+04 -9.93e+04  1.90e+06  4.57e+05  9.93e+04  1.90e+06 -3.90e+05  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-9.93e+04 -1.50e+05 -1.27e+06  9.93e+04  1.58e+05  6.15e+06  0.00e+00 -7.42e+03  7.42e+06  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-1.90e+06  1.27e+06  2.74e+09  1.90e+06  6.15e+06  1.54e+10  0.00e+00 -7.42e+06  4.95e+09  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00 -3.90e+05  0.00e+00  0.00e+00  1.17e+06  0.00e