In [1]:
from fem.core.Node         import Node
from fem.core.Material     import Material
from fem.sections.Membrane import Membrane

from fem.elements.CST      import CST
from fem.elements.LST      import LST
from fem.elements.Quad4    import Quad4
from fem.elements.Quad9    import Quad9

import numpy as np



  FEM -- Finite Element Method for Structural Analysis
  Based on the course by Prof. José Abell

  Version 0.1.0                        © 2026 All Rights Reserved

  Repository  :  https://github.com/ppalacios92/FEM
  Web Book    :  https://books.nmorabowen.com/books/fem

  Patricio Palacios B.    |    Nicolas Mora Bowen

  ********* (>'-')> Ladruño4ever  *********



In [2]:
# Material
Steel = Material(name='Steel', E=0.0, nu=0.3, rho=0.0 , printSummary=True)
F1    = Membrane(name='Plate', thickness=1.0, material=Steel)

-------------------------------------------------------------
Material properties:
Name: Steel
E: 0.00e+00
nu: 0.300
rho: 0.0
-------------------------------------------------------------



In [3]:
# Monkey patch directo
Steel.get_Emat = lambda type=None: np.array([
    [4, 1, 0],
    [1, 4, 0],
    [0, 0, 2],
]) * 8

# Verificar
print(Steel.get_Emat())

[[32  8  0]
 [ 8 32  0]
 [ 0  0 16]]


In [4]:
# Verificar
print(Steel.get_Emat())

[[32  8  0]
 [ 8 32  0]
 [ 0  0 16]]


In [5]:
# Nodes
n1 = Node(0, [0.0, 0.0])
n2 = Node(1, [3.0, 1.0])
n3 = Node(2, [2.0, 2.0])

In [6]:
# Element
e1 = CST(element_tag=1, 
        node_list=[n1, n2, n3], 
        section=F1)


In [7]:
# Outputs
print("Area:")
print(e1.area)

print("\nB matrix:")
print(e1.get_B_matrix())

print("\nN at centroid:")
centroid = e1.get_centroid()
print("Centroid:", centroid)
print(e1.get_interpolation_matrix(*centroid))

print("\nK matrix:")
print(e1.get_stiffness_matrix())

Area:
2.0000000000000004

B matrix:
[[-0.25  0.    0.5   0.   -0.25  0.  ]
 [ 0.   -0.25  0.   -0.5   0.    0.75]
 [-0.25 -0.25 -0.5   0.5   0.75 -0.25]]

N at centroid:
Centroid: [1.66666667 1.        ]
[[ 1.          0.          0.33333333  0.         -0.33333333  0.        ]
 [ 0.          1.          0.          0.33333333  0.         -0.33333333]]

K matrix:
[[  6.   3.  -4.  -2.  -2.  -1.]
 [  3.   6.   2.   4.  -5. -10.]
 [ -4.   2.  24. -12. -20.  10.]
 [ -2.   4. -12.  24.  14. -28.]
 [ -2.  -5. -20.  14.  22.  -9.]
 [ -1. -10.  10. -28.  -9.  38.]]
